### ISSUE TITLE
DHCP Damon crash on Release()

### ISSUE THREAD

**Issue by ramukima** [containernetworking/plugins#105]
Running CNI IPAM plugin (dhcp) on a network managed by libvirt (NATed)...

Everything looks good except for when I delete my services/pods, I see the following in the DHCP daemon output and it crashes.

Jan 04 22:19:17 sdp dhcp[14769]: panic: close of closed channel
Jan 04 22:19:17 sdp dhcp[14769]: goroutine 38 [running]:
Jan 04 22:19:17 sdp dhcp[14769]: main.(*DHCPLease).Stop(0xc4200bc7e0)
Jan 04 22:19:17 sdp dhcp[14769]:         /opt/src/gopath/src/github.com/containernetworking/plugin
Jan 04 22:19:17 sdp dhcp[14769]: main.(*DHCP).Release(0xc42000f400, 0xc420194690, 0xa5c238, 0x0, 0
Jan 04 22:19:17 sdp dhcp[14769]:         /opt/src/gopath/src/github.com/containernetworking/plugin
Jan 04 22:19:17 sdp dhcp[14769]: reflect.Value.call(0xc420046360, 0xc42000c140, 0x13, 0x8444a6, 0x
Jan 04 22:19:17 sdp dhcp[14769]:         /usr/local/go/src/reflect/value.go:434 +0x91f
Jan 04 22:19:17 sdp dhcp[14769]: reflect.Value.Call(0xc420046360, 0xc42000c140, 0x13, 0xc42001e720
Jan 04 22:19:17 sdp dhcp[14769]:         /usr/local/go/src/reflect/value.go:302 +0xa4
Jan 04 22:19:17 sdp dhcp[14769]: net/rpc.(*service).call(0xc42003b980, 0xc42003b8c0, 0xc4201825e0,
Jan 04 22:19:17 sdp dhcp[14769]:         /usr/local/go/src/net/rpc/server.go:387 +0x144
Jan 04 22:19:17 sdp dhcp[14769]: created by net/rpc.(*Server).ServeCodec
Jan 04 22:19:17 sdp dhcp[14769]:         /usr/local/go/src/net/rpc/server.go:481 +0x404
J

**Comment by ramukima** [comment]
I also see this in /var/log/syslog -

cni.go:265] CNI failed to retrieve network namespace path: Cannot find network namespace for the terminated container "80980b7cdc277e26f740b302487ea654b78332e5119f3b614d313863caf50212"

cni.go:319] Error deleting network: error dialing DHCP daemon: error calling DHCP.Release: lease not found: 80980b7cdc277e26f740b302487ea654b78332e5119f3b614d313863caf50212/cni0

**Comment by ramukima** [comment]
Could it be related to this -
 https://github.com/containernetworking/plugins/commit/cc714265926d48ae626b776dc3ffed41d1aab101
