### ISSUE TITLE
[panic] panic happened when use portmap

### ISSUE THREAD

**Issue by heartlock** [containernetworking/plugins#19]
```
panic: interface conversion: error is *os.PathError, not *exec.ExitError

goroutine 1 [running]:
panic(0x544a40, 0xc4200cd080)
	/home/travis/.gimme/versions/go1.7.5.linux.amd64/src/runtime/panic.go:500 +0x1a1
github.com/containernetworking/plugins/vendor/github.com/coreos/go-iptables/iptables.(*IPTables).runWithOutput(0xc420015dc0, 0xc4200ee1a0, 0xe, 0x1a, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/containernetworking/plugins/gopath/src/github.com/containernetworking/plugins/vendor/github.com/coreos/go-iptables/iptables/iptables.go:257 +0x4ad
github.com/containernetworking/plugins/vendor/github.com/coreos/go-iptables/iptables.(*IPTables).run(0xc420015dc0, 0xc4200f6180, 0xc, 0xc, 0xc4200ce500, 0x8)
	/home/travis/gopath/src/github.com/containernetworking/plugins/gopath/src/github.com/containernetworking/plugins/vendor/github.com/coreos/go-iptables/iptables/iptables.go:227 +0x5b
github.com/containernetworking/plugins/vendor/github.com/coreos/go-iptables/iptables.(*IPTables).Exists(0xc420015dc0, 0x56d519, 0x3, 0xc420010990, 0x1c, 0xc4200ce500, 0x8, 0x8, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/containernetworking/plugins/gopath/src/github.com/containernetworking/plugins/vendor/github.com/coreos/go-iptables/iptables/iptables.go:95 +0x1a6
main.prependUnique(0xc420015dc0, 0x56d519, 0x3, 0xc420010990, 0x1c, 0xc4200ce500, 0x8, 0x8, 0xc42000ce08, 0x1)
	/home/travis/gopath/src/github.com/containernetworking/plugins/gopath/src/github.com/containernetworking/plugins/plugins/meta/portmap/chain.go:104 +0x84
main.(*chain).setup(0xc42005bbd0, 0xc420015dc0, 0xc4200c1f60, 0x1, 0x1, 0x10, 0xc4200c1f60)
	/home/travis/gopath/src/github.com/containernetworking/plugins/gopath/src/github.com/containernetworking/plugins/plugins/meta/portmap/chain.go:47 +0x113
main.forwardPorts(0xc4200181e0, 0xc42000d220, 0x10, 0x10, 0x1, 0x0)
	/home/travis/gopath/src/github.com/containernetworking/plugins/gopath/src/github.com/containernetworking/plugins/plugins/meta/portmap/portmap.go:84 +0x428
main.cmdAdd(0xc420026690, 0xc42000c930, 0x5)
	/home/travis/gopath/src/github.com/containernetworking/plugins/gopath/src/github.com/containernetworking/plugins/plugins/meta/portmap/main.go:93 +0x1d8
github.com/containernetworking/plugins/vendor/github.com/containernetworking/cni/pkg/skel.(*dispatcher).checkVersionAndCall(0xc420016440, 0xc420026690, 0x815820, 0xc420012c30, 0x57f748, 0x0, 0x30)
	/home/travis/gopath/src/github.com/containernetworking/plugins/gopath/src/github.com/containernetworking/plugins/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:162 +0x175
github.com/containernetworking/plugins/vendor/github.com/containernetworking/cni/pkg/skel.(*dispatcher).pluginMain(0xc420016440, 0x57f748, 0x57f750, 0x815820, 0xc420012c30, 0x50)
	/home/travis/gopath/src/github.com/containernetworking/plugins/gopath/src/github.com/containernetworking/plugins/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:173 +0x372
github.com/containernetworking/plugins/vendor/github.com/containernetworking/cni/pkg/skel.PluginMainWithError(0x57f748, 0x57f750, 0x815820, 0xc420012c30, 0x489040)
	/home/travis/gopath/src/github.com/containernetworking/plugins/gopath/src/github.com/containernetworking/plugins/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:210 +0xf0
github.com/containernetworking/plugins/vendor/github.com/containernetworking/cni/pkg/skel.PluginMain(0x57f748, 0x57f750, 0x815820, 0xc420012c30)
	/home/travis/gopath/src/github.com/containernetworking/plugins/gopath/src/github.com/containernetworking/plugins/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:222 +0x63
main.main()
	/home/travis/gopath/src/github.com/containernetworking/plugins/gopath/src/github.com/containernetworking/plugins/plugins/meta/portmap/main.go:125 +0xc8
```
@squeed  I think we should fix it.
ref: https://github.com/coreos/go-iptables/issues/35, https://github.com/coreos/go-iptables/pull/37

**Comment by feiskyer** [comment]
@heartlock Would you like file a PR to fix the problem?

**Comment by heartlock** [comment]
@feiskyer Of course, will do it.

**Comment by lucab** [comment]
Ping back from https://github.com/coreos/go-iptables/pull/37, fix landed in https://github.com/coreos/go-iptables/pull/39. Does CNI need a tagged release to bump to?

/cc @squeed
